name: Build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install blas and lapack
      run: sudo apt install -y blas lapack
    - name: build
      run: make clean ; make
    - name: tests
      run: cd examples ; ./clean.sh ; ./run-all.sh single
